### PR TITLE
fix(reports): convey remote report generation status codes to client

### LINKED ISSUE #567: Extract TempFileProvider to FileSysten
https://github.com/cryostatio/cryostat/blob/74328d3268156f001b8977ab769601da7a3e2fd5/src/main/java/io/cryostat/net/reports/SubprocessReportGenerator.java#L91

### LINKED ISSUE #795: Remote report generator deficiencies
https://github.com/cryostatio/cryostat/blob/8347e65e09eb46db9624e4f9b31e27202c03604e/src/main/java/io/cryostat/net/reports/ReportsModule.java#L75

https://github.com/cryostatio/cryostat/blob/8347e65e09eb46db9624e4f9b31e27202c03604e/src/main/java/io/cryostat/net/reports/ReportsModule.java#L137 / https://github.com/cryostatio/cryostat/blob/8347e65e09eb46db9624e4f9b31e27202c03604e/src/main/java/io/cryostat/net/reports/AbstractReportGeneratorService.java#L68 ( see also: https://github.com/cryostatio/cryostat-core/pull/54 )

https://github.com/cryostatio/cryostat/blob/8347e65e09eb46db9624e4f9b31e27202c03604e/src/main/java/io/cryostat/net/web/http/api/beta/TargetReportGetHandler.java#L144 - 404, 413, and 504 are all common error codes that should also be handled and properly forwarded to the requesting client. https://github.com/cryostatio/cryostat-reports/pull/11#discussion_r778976116

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #795
Fixes #567
Depends on https://github.com/cryostatio/cryostat-core/issues/113

Easy way to test: modify `smoketest.sh` similarly to the `-reports` `run.sh` (https://github.com/cryostatio/cryostat-reports/blob/3237998ca88710a5537b13d0bd4f742caf8b32d4/run.sh#L33). Add `-Dio.cryostat.reports.memory-factor=${MEMORY_FACTOR}` or `-Dio.cryostat.reports.timeout=${TIMEOUT}` to the `smoketest.sh` `JAVA_OPTIONS` for the report generator container with `${MEMORY_FACTOR}`/`${TIMEOUT}` replaced with some reduced value to induce a 413/504 response from the report sidecar. Then make a report request through the Cryostat HTTP API as usual (`GET /api/v1/recordings/foo` or `GET /api/v1/targets/foo/reports/bar`).

### CODE REVIEW

File: src/main/java/io/cryostat/net/reports/AbstractReportGeneratorService.java [hunk 1]
```diff
@@ -65,18 +63,12 @@
 
     protected final TargetConnectionManager targetConnectionManager;
     protected final FileSystem fs;
-    // FIXME extract TempFileProvider to FileSystem
```
Comment (jan-law) [inline src/main/java/io/cryostat/net/reports/AbstractReportGeneratorService.java:68]: Does this PR also fix #567 as well? If so, could we also remove the `tempFileProvider` object at https://github.com/cryostatio/cryostat/blob/main/src/test/java/io/cryostat/net/reports/ActiveRecordingReportCacheTest.java#L79 ? It looks like it's unused.

**Review by jan-law — COMMENTED** [review]
The exception handling is working well for me with smoketest. Besides my one question, the code also looks good.
```
jalaw@localhost ~/Downloads> curl -v http://0.0.0.0:8181/api/v1/reports/janlaw-6f4775cdbf-82dvl_10mb_20211006T152006Z.jfr
*   Trying 0.0.0.0:8181...
* Connected to 0.0.0.0 (127.0.0.1) port 8181 (#0)
> GET /api/v1/reports/janlaw-6f4775cdbf-82dvl_10mb_20211006T152006Z.jfr HTTP/1.1
> Host: 0.0.0.0:8181
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 413 Request Entity Too Large
< content-type: text/plain
< content-length: 172
< 
* Connection #0 to host 0.0.0.0 left intact
java.util.concurrent.ExecutionException: io.cryostat.net.reports.ReportGenerationException: Request Entity Too Large caused by HttpStatusException: Request Entity Too Large⏎                                                                                     jalaw@localhost ~/Downloads> curl -v http://0.0.0.0:8181/api/v1/reports/janlaw-6f4775cdbf-82dvl_10mb_20211006T152006Z.jfr
*   Trying 0.0.0.0:8181...
* Connected to 0.0.0.0 (127.0.0.1) port 8181 (#0)
> GET /api/v1/reports/janlaw-6f4775cdbf-82dvl_10mb_20211006T152006Z.jfr HTTP/1.1
> Host: 0.0.0.0:8181
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 504 Gateway Timeout
< content-type: text/plain
< content-length: 154
< 
* Connection #0 to host 0.0.0.0 left intact
java.util.concurrent.ExecutionException: io.cryostat.net.reports.ReportGenerationException: Gateway Timeout caused by HttpStatusException: Gateway Timeout                                                                                                  
```

File: src/main/java/io/cryostat/net/reports/AbstractReportGeneratorService.java (hunk 1 above)
Comment (andrewazores) [reply src/main/java/io/cryostat/net/reports/AbstractReportGeneratorService.java:68]: Ah right, that's where the issue for it was. I thought it was filed in -core but couldn't find it - no wonder why.

**Review by hareetd — APPROVED** [review]
The exception handling works well.
