### PR TITLE
fix(archives): fix recording deletion notifications do not update All-Archives view and fixed README typo

### LINKED ISSUE #1023: [Task] cryostat README.md typo for sha256 command
In the docs, under https://github.com/cryostatio/cryostat/blob/main/README.md#user-authentication--authorization

It says

> Where abc123 and def987 are substituted for the SHA-256 sum hexes of the desired user passwords. These can be obtained by ex. `echo -n PASS | sha256sum | cut -d' ' -f1'`.

`echo -n PASS | sha256sum | cut -d' ' -f1'`
should be 
`echo -n PASS | sha256sum | cut -d' ' -f1`

### LINKED ISSUE #1098: [Task] Recording deletion notifications do not update All-Archives view
Backend of https://github.com/cryostatio/cryostat-web/issues/536

### PR DESCRIPTION
**Pull request by maxcao13**
Fixes #1098 
Fixes #1023 
Fixes https://github.com/cryostatio/cryostat-web/issues/536

Just missed one more Periodic Archiver method change, oops.

### CODE REVIEW

**Review by tthvo — APPROVED** [review]
Looks good! The issue is fixed on the web :D

File: src/main/java/io/cryostat/rules/PeriodicArchiver.java [hunk 1]
```diff
@@ -150,7 +150,9 @@ private void performArchival() throws InterruptedException, ExecutionException,
     }
 
     private void pruneArchive(String recordingName) throws Exception {
-        recordingArchiveHelper.deleteRecording(recordingName).get();
+        recordingArchiveHelper
+                .deleteRecording(serviceRef.getServiceUri().toString(), recordingName)
```
Comment (andrewazores) [inline src/main/java/io/cryostat/rules/PeriodicArchiver.java:154]: For a potential future refactor, should this first `String targetId/connectUrl` parameter be replaced with the whole `ServiceRef` to signify the sourceTarget? Only the connectUrl or jvmId is probably actually relevant, but it gives the option to use either of those as well as provides some compile-time type safety to guard against accidents like this one.

**Review by andrewazores — APPROVED** [review]
