### PR TITLE
fix(api): fix GET /api serialization and webserver JFR event

### LINKED ISSUE #1191: [Task] Mismatched event name between impl and self-inspection template
https://github.com/cryostatio/cryostat/blob/35b8625035e880278d152fc0d7cc693bee775cbf/src/container/include/cryostat.jfc#L33

https://github.com/cryostatio/cryostat/blob/35b8625035e880278d152fc0d7cc693bee775cbf/src/main/java/io/cryostat/net/web/WebServer.java#L276

### LINKED ISSUE #1192: [Task] Badly-serialized `GET /api` response
```
 http :8181/api
HTTP/1.1 200 OK
content-encoding: gzip
content-length: 900
content-type: application/json
vary: origin
```

produces this, with a badly-serialized `verb` for each entry:

```json
{
    "data": {
        "result": {
            "endpoints": [
                {
                    "path": "/api/beta/fs/recordings",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/fs/recordings/:subdirectoryName/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/fs/recordings/:subdirectoryName/:recordingName/jwt",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/fs/recordings/:subdirectoryName/:recordingName/metadata/labels",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/fs/recordings/:subdirectoryName/:recordingName/upload",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/fs/reports/:subdirectoryName/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/fs/reports/:subdirectoryName/:recordingName/jwt",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/recordings/:sourceTarget/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/recordings/:sourceTarget/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/recordings/:sourceTarget/:recordingName/jwt",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/recordings/:sourceTarget/:recordingName/metadata/labels",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/recordings/:sourceTarget/:recordingName/upload",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/reports/:sourceTarget/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/reports/:sourceTarget/:recordingName/jwt",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/beta/targets/:targetId/recordings/:recordingName/metadata/labels",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "BETA"
                },
                {
                    "path": "/api/v1/auth",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/grafana_dashboard_url",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/grafana_datasource_url",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/notifications_url",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/recordings",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/recordings",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/recordings/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/recordings/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/recordings/:recordingName/upload",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/reports/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/events",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/recordingOptions",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/recordingOptions",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 5,
                                "offset": 0,
                                "string": "PATCH",
                                "value": [
                                    80,
                                    65,
                                    84,
                                    67,
                                    72
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/recordings",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/recordings",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/recordings/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 5,
                                "offset": 0,
                                "string": "PATCH",
                                "value": [
                                    80,
                                    65,
                                    84,
                                    67,
                                    72
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/recordings/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/recordings/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/recordings/:recordingName/upload",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/reports/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/snapshot",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/templates",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/targets/:targetId/templates/:templateName/type/:templateType",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/templates",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v1/templates/:templateName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "V1"
                },
                {
                    "path": "/api/v2.1/auth",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_1"
                },
                {
                    "path": "/api/v2.1/auth/token",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_1"
                },
                {
                    "path": "/api/v2.1/credentials",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_1"
                },
                {
                    "path": "/api/v2.1/discovery",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_1"
                },
                {
                    "path": "/api/v2.1/logout",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_1"
                },
                {
                    "path": "/api/v2.1/recordings/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_1"
                },
                {
                    "path": "/api/v2.1/reports/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_1"
                },
                {
                    "path": "/api/v2.1/targets/:targetId/recordings/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_1"
                },
                {
                    "path": "/api/v2.1/targets/:targetId/reports/:recordingName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_1"
                },
                {
                    "path": "/api/v2.1/targets/:targetId/templates/:templateName/type/:templateType",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_1"
                },
                {
                    "path": "/api/v2.2/credentials",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_2"
                },
                {
                    "path": "/api/v2.2/credentials",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_2"
                },
                {
                    "path": "/api/v2.2/credentials/:id",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_2"
                },
                {
                    "path": "/api/v2.2/credentials/:id",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "V2_2"
                },
                {
                    "path": "/api/v2.2/discovery",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_2"
                },
                {
                    "path": "/api/v2.2/discovery/:id",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_2"
                },
                {
                    "path": "/api/v2.2/discovery/:id",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "V2_2"
                },
                {
                    "path": "/api/v2.2/graphiql/*",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_2"
                },
                {
                    "path": "/api/v2.2/graphql",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_2"
                },
                {
                    "path": "/api/v2.2/graphql",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2_2"
                },
                {
                    "path": "/api/v2/certificates",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/probes",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/probes/:probetemplateName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/probes/:probetemplateName",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/rules",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/rules",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/rules/:name",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 5,
                                "offset": 0,
                                "string": "PATCH",
                                "value": [
                                    80,
                                    65,
                                    84,
                                    67,
                                    72
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/rules/:name",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/rules/:name",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/targets",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/targets/:targetId",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/targets/:targetId/credentials",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/targets/:targetId/credentials",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/targets/:targetId/events",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/targets/:targetId/probes",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 6,
                                "offset": 0,
                                "string": "DELETE",
                                "value": [
                                    68,
                                    69,
                                    76,
                                    69,
                                    84,
                                    69
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/targets/:targetId/probes",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/targets/:targetId/probes/:probeTemplate",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/targets/:targetId/recordingOptionsList",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 3,
                                "offset": 0,
                                "string": "GET",
                                "value": [
                                    71,
                                    69,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                },
                {
                    "path": "/api/v2/targets/:targetId/snapshot",
                    "verb": {
                        "nettyMethod": {
                            "name": {
                                "hash": 0,
                                "length": 4,
                                "offset": 0,
                                "string": "POST",
                                "value": [
                                    80,
                                    79,
                                    83,
                                    84
                                ]
                            }
                        }
                    },
                    "version": "V2"
                }
            ],
            "overview": "http://localhost:8181/HTTP_API.md"
        }
    },
    "meta": {
        "status": "OK",
        "type": "application/json"
    }
}
```

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #1191
Fixes #1192

- fix(api): GET /api returns properly serialized endpoint verb
- chore(log): replace request logging with Vertx impl
- correct event name and move into logging handler

### CODE REVIEW

**Comment by andrewazores** [comment]
Marked with `backport` label though I think it's too late to get this in to `2.2.0`. These are lower-priority fixes solving problems that most users won't run into so if a `2.2.1` happens then this can get pulled in.

**Review by maxcao13 — COMMENTED** [review]
Everything looks good to me. 

Should there be a test suite for RequestLoggingHandler? 
For example testing the basic API specs,  and that a WebServerRequest event is really emitted during a handling of some fake RequestHandler perhaps.

File: src/main/java/io/cryostat/Cryostat.java [hunk 1]
```diff
@@ -141,6 +143,10 @@ private void shutdown(Throwable cause) {
 
     public static void main(String[] args) throws IOException {
         final Client client = DaggerCryostat_Client.builder().build();
+        try (InputStream config = CryostatCore.class.getResourceAsStream("/logging.properties")) {
+            LogManager.getLogManager()
+                    .updateConfiguration(config, k -> ((o, n) -> o != null ? o : n));
```
Comment (tthvo) [inline src/main/java/io/cryostat/Cryostat.java:148]: For these configurations, should we use the new configurations over the old ones if exist instead?

Comment (tthvo) [reply src/main/java/io/cryostat/Cryostat.java]: Nice! Also again on this note, I notice now we just replace with all new configs. Should we merge new properties and old ones (i.e. if a new property is specified, use it. Otherwise use the default/old ones)?

Comment (andrewazores) [reply src/main/java/io/cryostat/Cryostat.java]: Potentially sure, but in practice this is the `main` method and the first instance of any config being loaded anyway. The `CryostatCore.initialize()` actually tries to set some defaults of its own too, so I did this first here to set values that the `-core` won't override since there are already defined values for the keys. Hard to say from this perspective what the "right" behaviour is for selecting a value in a generic way, right now we just need these specific values to be set.

**Review by maxcao13 — DISMISSED** [review]
LGTM

File: src/main/java/io/cryostat/Cryostat.java (hunk 1 above)
Comment (tthvo) [reply src/main/java/io/cryostat/Cryostat.java]: Right that makes sense! Thanks for explaining :D

File: src/main/java/io/cryostat/net/web/http/generic/RequestLoggingHandler.java [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+        return ResourceAction.NONE;
+    }
+
+    @Override
+    public String path() {
+        return ALL_PATHS;
+    }
+
+    @Override
+    public void handle(RoutingContext event) {
```
Comment (tthvo) [inline src/main/java/io/cryostat/net/web/http/generic/RequestLoggingHandler.java:93]: Should be named `ctx` to match other routes?

**Review by tthvo — APPROVED** [review]
Looks great to me :D

**Comment by andrewazores** [comment]
> Marked with `backport` label though I think it's too late to get this in to `2.2.0`. These are lower-priority fixes solving problems that most users won't run into so if a `2.2.1` happens then this can get pulled in.

Actually... this would end up in the upstream `2.2.0` but it's too late for the downstream `2.2.0`. Doesn't seem to make sense. I'll remove the label.
