### PR TITLE
test(itest): make test host configurable

### LINKED ISSUE #572: itests should not hardcode 0.0.0.0
I recently started seeing this failure on integration tests locally:

```
[WARN] [stderr] io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /0.0.0.0:8181
[WARN] [stderr] Caused by: java.net.NoRouteToHostException: No route to host
[WARN] [stderr] 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[WARN] [stderr] 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[WARN] [stderr] 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
[WARN] [stderr] 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[WARN] [stderr] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
[WARN] [stderr] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
[WARN] [stderr] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
[WARN] [stderr] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[WARN] [stderr] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[WARN] [stderr] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[WARN] [stderr] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[WARN] [stderr] 	at java.base/java.lang.Thread.run(Thread.java:829)
```

itests should not assume 0.0.0.0 - this should be configurable, and perhaps should default to `localhost` instead anyway.

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #572

### CODE REVIEW

File: run.sh [hunk 1]
```diff
@@ -31,18 +31,6 @@ if [ -z "$CRYOSTAT_EXT_WEB_PORT" ]; then
     CRYOSTAT_EXT_WEB_PORT="$CRYOSTAT_WEB_PORT"
 fi
 
-if [ -z "$CRYOSTAT_LISTEN_HOST" ]; then
-    CRYOSTAT_LISTEN_HOST="$CRYOSTAT_WEB_HOST"
```
Comment (jan-law) [inline run.sh:35]: Was the `LISTEN_PORT` originally used for the two-way notifications channel?

Comment (andrewazores) [reply run.sh:35]: Sort of - it's even older than that. It was used for the original interactive "shell" execution mode, when I extended that to work over TCP sockets instead of only over stdin/stdout in a terminal.

**Review by hareetd — APPROVED** [review]
Looks good!
