### PR TITLE
fix(graphQL): Restrict GraphiQL availability to dev mode

### LINKED ISSUE #819: GraphiQL handler should only be available in an explicit dev mode
https://github.com/cryostatio/cryostat/blob/a00358d379bb23e8833f028edbab51aca86f120b/src/main/java/io/cryostat/net/web/http/api/beta/graph/GraphiQLGetHandler.java#L83

We don't currently have an exact "dev mode" environment variable for Cryostat. The closest thing would be the `CRYOSTAT_CORS_ORIGIN`, but that is not quite right.

### PR DESCRIPTION
**Pull request by jan-law**
Fixes #819 

The GraphiQL web page is only available at `https://localhost:8181/api/beta/graphiql/` when running cryostat with `CRYOSTAT_DEV_MODE=true`.

### CODE REVIEW

**Review by andrewazores — APPROVED** [review]

**Review by andrewazores — APPROVED** [review]
Actually - could you also update the `devserver.sh` to set the dev mode env var to true?

File: src/main/java/io/cryostat/configuration/Variables.java [hunk 1]
```diff
@@ -69,6 +69,7 @@ private Variables() {}
     public static final String MAX_CONNECTIONS_ENV_VAR = "CRYOSTAT_MAX_WS_CONNECTIONS";
     public static final String ENABLE_CORS_ENV = "CRYOSTAT_CORS_ORIGIN";
     public static final String HTTP_REQUEST_TIMEOUT = "CRYOSTAT_HTTP_REQUEST_TIMEOUT";
+    public static final String WEB_ENV_DEV_MODE = "CRYOSTAT_WEB_ENV_DEV_MODE";
```
Comment (andrewazores) [inline src/main/java/io/cryostat/configuration/Variables.java:72]: WDYT about just calling this `CRYOSTAT_DEV_MODE`?

Comment (jan-law) [reply src/main/java/io/cryostat/configuration/Variables.java:72]: Sure, sounds good

**Review by andrewazores — APPROVED** [review]

File: devserver.sh [hunk 2]
```diff
@@ -109,4 +109,5 @@ MAVEN_OPTS="${flags[@]}" \
     CRYOSTAT_CONFIG_PATH="${work_dir}/conf" \
     CRYOSTAT_TEMPLATE_PATH="${work_dir}/templates" \
     CRYOSTAT_PROBE_TEMPLATE_PATH="${work_dir}/probes" \
+    CRYOSTAT_WEB_ENV_DEV_MODE=true \
```
Comment (andrewazores) [inline devserver.sh:112]: Rename here too

**Review by andrewazores — CHANGES_REQUESTED** [review]

**Review by andrewazores — APPROVED** [review]
