### PR TITLE
fix(discovery): discovery plugin register/update errors respond 4xx

### LINKED ISSUE #1054: [Task] Discovery plugin registration failure due to duplicate realm/callback responds with `HTTP 500`
https://github.com/cryostatio/cryostat/pull/1052#discussion_r951691681

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #1054

- test(discovery): add discovery plugin itest
- fix(discovery): respond 400 on duplicate registration attempt
- fix(discovery): respond 400 on update unregistered ID attempt
- chore(itest): remove unused command-response methods

Result from `bash repeated-integration-tests.bash 1 DiscoveryPluginIT` with only the first commit applied (test addition, no fixes):

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running itest.DiscoveryPluginIT
[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.465 s <<< FAILURE! - in itest.DiscoveryPluginIT
[ERROR] shouldFailToReregister  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError:

Expected: <400>
     but: was <500>
	at itest.DiscoveryPluginIT.shouldFailToReregister(DiscoveryPluginIT.java:146)
[ERROR] shouldFailToUpdateUnregisteredPluginID  Time elapsed: 0.005 s  <<< FAILURE!
java.lang.AssertionError:

Expected: <404>
     but: was <500>
	at itest.DiscoveryPluginIT.shouldFailToUpdateUnregisteredPluginID(DiscoveryPluginIT.java:202)
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   DiscoveryPluginIT.shouldFailToReregister:146
Expected: <400>
     but: was <500>
[ERROR]   DiscoveryPluginIT.shouldFailToUpdateUnregisteredPluginID:202
Expected: <404>
     but: was <500>
[INFO]
[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 0
```

With the fixes applied, the test cases all pass.

### CODE REVIEW

File: src/test/java/itest/DiscoveryPluginIT.java [hunk 1]
```diff
@@ -0,0 +1,204 @@
...
+        CompletableFuture<Buffer> response = new CompletableFuture<>();
+        webClient
+                .post("/api/v2.2/discovery/" + id)
+                .sendJson(
+                        subtree,
+                        ar -> {
+                            assertRequestStatus(ar, response);
+                            response.complete(ar.result().body());
+                        });
+        response.get();
```
Comment (tthvo) [inline src/test/java/itest/DiscoveryPluginIT.java:129]: Should we check response status here too?

File: src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryPostHandler.java [hunk 2]
```diff
@@ -131,6 +132,8 @@ public IntermediateResponse<Void> handle(RequestParameters params) throws Except
             return new IntermediateResponse<Void>().body(null);
         } catch (JsonSyntaxException | IllegalArgumentException e) {
```
Comment (tthvo) [inline src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryPostHandler.java:133]: In the case of schema violation (e.g. null primary key), I am a bit unsure which Exception will be thrown. Same for `DiscoveryRegistrationHandler`?

Comment (tthvo) [reply src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryPostHandler.java:133]: Should we also add these cases of violation to `DiscoveryPluginIT` test?

File: src/test/java/itest/DiscoveryPluginIT.java (hunk 1 above)
Comment (andrewazores) [reply src/test/java/itest/DiscoveryPluginIT.java:129]: It's hidden, but it does:

https://github.com/cryostatio/cryostat/blob/5517451aab07988b521887253b94364f34c478fe/src/test/java/itest/bases/StandardSelfTest.java#L126

This checks for `2xx` codes.

File: src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryPostHandler.java (hunk 2 above)
Comment (andrewazores) [reply src/main/java/io/cryostat/net/web/http/api/v2/DiscoveryPostHandler.java:133]: The `PluginInfo` primary key is a UUID generated by the database, so it can't be nulled by the registering client. If they try to register with a null/empty realm or callback URI then it's an` IllegalArgumentException` via `requireNonBlank`. If the subtree they provide is not a valid JSON document then it's a `JsonSyntaxException`.

File: src/test/java/itest/DiscoveryPluginIT.java [hunk 3]
```diff
@@ -0,0 +1,318 @@
...
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.TestMethodOrder;
+
+@TestMethodOrder(OrderAnnotation.class)
+class DiscoveryPluginIT extends StandardSelfTest {
+
+    private static final Gson gson =
+            new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create();
+
+    static final NodeType NODE_TYPE =
```
Comment (tthvo) [inline src/test/java/itest/DiscoveryPluginIT.java:68]: I think we can remove these `NODE_TYPE` and `gson` fields since they are not used?

**Review by tthvo — APPROVED** [review]
Looks great :D Nicee fix!
