### PR TITLE
fix(k8s-rbac): update permission mapping between k8s and cryostat

### LINKED ISSUE #979: [Task] Select default permissions that do not use FlightRecorder/Recording
After #635, we can modify which Cryostat permissions map to which Kubernetes RBAC permissions. Now we should modify the default Kubernetes permissions from their current values. Since the FlightRecorder and Recordings APIs will soon be removed, we have to pick some alternatives. Ideally these would not depend on CRDs shipped with the operator, but that's not a hard requirement, it would simply allow for more flexibility.

### PR DESCRIPTION
**Pull request by tthvo**
Fixes #979 
Related to https://github.com/cryostatio/cryostat-operator/pull/440

Use alternatives for mapping between k8s resource to cryostat since flightRecorder/Recordings are deprecated.

### CODE REVIEW

File: src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties [hunk 1]
```diff
@@ -8,7 +8,7 @@
 # RECORDINGS="recordings.operator.cryostat.io"
 
 # ResourceType to Kubernetes resource kind mapping:
-TARGET=flightrecorders.operator.cryostat.io
-RECORDING=recordings.operator.cryostat.io
+TARGET=pods,deployments.apps
```
Comment (tthvo) [inline src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties:11]: For targets, I wonder if `endpoints` is also necessary? My thinking is that discovery mechanism needs access endpoint resource so it should be declared here.

Comment (andrewazores) [reply src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties:11]: Makes sense to me.

**Comment by tthvo** [comment]
Marked as draft to update tests and check with running cluster.

File: src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties (hunk 1 above)
Comment (ebaron) [reply src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties]: I just stumbled across this note that write access to Endpoints objects is going to be forbidden in most scenarios in Kubernetes 1.22+: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#write-access-for-endpoints

This may make `CREATE`, `UPDATE`, `DELETE` operations on targets difficult if we include Endpoints.

Comment (andrewazores) [reply src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties]: Fair enough. One way around would be to differentiate between normally discovered targets (readonly) and custom targets (all verbs), but that feels like a bit of a hack.

Comment (tthvo) [reply src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties]: For that security issue, I think we could remove it. I was looking into a replacement but I wonder if a more "
abstract" object like `service` is a good alternative?

Comment (ebaron) [reply src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties]: Service seems like a reasonable substitute since they're so closely coupled.

Comment (ebaron) [reply src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties]: These are all somewhat arbitrarily chosen, it would be good to allow users to configure this permissions mapping file from the operator. I'm not sure if we have an existing issue for that.

Comment (tthvo) [reply src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties]: Hmm I cant see one but I only remember Andrew mentioned it in this issue https://github.com/cryostatio/cryostat/issues/979#issuecomment-1146325376. In this case, we will allow some config in Cryostat for this mapping, right?

Comment (andrewazores) [reply src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties]: The file you edited in this PR is that mapping file, see #662 . There may be a bit more work required to make this something that the Operator can replace at runtime, but the idea is that the Operator could just mount a replacement file overtop of this default one in the container image.

Comment (ebaron) [reply src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties]: I filed an issue in the operator for this feature: https://github.com/cryostatio/cryostat-operator/issues/439

Comment (tthvo) [reply src/main/resources/io/cryostat/net/openshift/OpenShiftAuthManager.properties]: Nicee! I will dig more into this auth flow and look at the new issue too!

**Comment by tthvo** [comment]
Currently, this is my idea for refining the mappings:

``` bash
# Access pods (i.e application) and establish connections (i.e. using service instead of endpoints)
TARGET=pods,services 
# Access Cryostat to operate recordings
RECORDING=pods,pods/exec,cryostats.operator.cryostat.io
# Mount certificates from secrets into Cryostat
CERTIFICATE=pods,secrets,cryostats.operator.cryostat.io 
# Access Cryostat to add credentials (i.e. via webUI I think)
CREDENTIALS=pods,cryostats.operator.cryostat.io 
```
Any thoughts @andrewazores @ebaron?

**Comment by ebaron** [comment]
> Currently, this is my idea for refining the mappings:
> 
> ```shell
> # Access pods (i.e application) and establish connections (i.e. using service instead of endpoints)
> TARGET=pods,services 
> # Access Cryostat to operate (i.e. execute) recordings
> RECORDING=pods,pods/exec,cryostats.operator.cryostat.io
> # Mount certificates from secrets into Cryostat
> CERTIFICATE=pods,secrets,cryostats.operator.cryostat.io 
> # Access Cryostat to add credentials (i.e. via webUI I think)
> CREDENTIALS=pods,cryostats.operator.cryostat.io 
> ```
> 
> Any thoughts @andrewazores @ebaron?

I think this is good. While the certificates themselves may not be sensitive, the act of telling Cryostat to trust them should be privileged. I would also add Secrets for credentials as well, since that is a common use case for Secrets in Kubernetes.

**Comment by tthvo** [comment]
@andrewazores  I believe #625 is resolved since #1037? Just come across a FIXME to disable reading `kubeconfig` in `OpenShiftAuthManagerTest`.

**Comment by andrewazores** [comment]
@tthvo thanks: https://github.com/cryostatio/cryostat/pull/1057

File: src/test/java/io/cryostat/net/openshift/OpenShiftAuthManagerTest.java [hunk 2]
```diff
@@ -358,8 +348,7 @@ void shouldNotValidateTokenWithInsufficientPermissions() throws Exception {
                 Matchers.instanceOf(PermissionDeniedException.class));
         PermissionDeniedException pde = (PermissionDeniedException) ExceptionUtils.getRootCause(ee);
         MatcherAssert.assertThat(pde.getNamespace(), Matchers.equalTo(NAMESPACE));
-        MatcherAssert.assertThat(
-                pde.getResourceType(), Matchers.equalTo("recordings.operator.cryostat.io"));
+        MatcherAssert.assertThat(pde.getResourceType(), Matchers.equalTo("pods/exec"));
```
Comment (tthvo) [inline src/test/java/io/cryostat/net/openshift/OpenShiftAuthManagerTest.java:351]: I just noticed that with this, we can only check the first resource denied. That means in our mock for `RECORDING` should only specify one k8s resource unless we have some orders. But I think it does not matter that much.

**Comment by tthvo** [comment]
@ebaron @andrewazores Ready for review :D

For tests, I just removed references in deprecated apis. There was no issue with subresource being used in tests (I thought it would be part of the `getResource` but using `getSubResource` is the right way).

File: src/test/java/io/cryostat/net/openshift/OpenShiftAuthManagerTest.java (hunk 2 above)
Comment (andrewazores) [reply src/test/java/io/cryostat/net/openshift/OpenShiftAuthManagerTest.java:341]: I think that's fine. Maybe in the future it's worth refactoring things so that all of the requested permissions are checked and the set of failures are all reported, but the important thing is that unauthorized requests don't get completed.

**Review by andrewazores — DISMISSED** [review]
LGTM

**Review by ebaron — DISMISSED** [review]
Seems good to me. This should probably be committed close to https://github.com/cryostatio/cryostat-operator/pull/440, otherwise the OAuth tokens will not have the correct set of permissions.

**Comment by tthvo** [comment]
Right, I will update https://github.com/cryostatio/cryostat-operator/pull/440 oauth role with these default permissions and tests it.

**Comment by tthvo** [comment]
Since including `Secrets` in mapping is denied due escalation security issue, I am thinking of its "closely" resembling resource `ConfigMap` though I am not sure if it is good alternative.

*See  original https://github.com/cryostatio/cryostat-operator/pull/440#issuecomment-1227443550*

**Comment by ebaron** [comment]
> Since including `Secrets` in mapping is denied due escalation security issue, I am thinking of its "closely" resembling resource `ConfigMap` though I am not sure if it is good alternative.
> 
> _See original [cryostatio/cryostat-operator#440 (comment)](https://github.com/cryostatio/cryostat-operator/pull/440#issuecomment-1227443550)_

Config Maps are similar, but not used for sensitive data, while Secrets are. I can't think of any other reasonable substitute though, so I'd say either use Config Maps or remove it entirely.

**Comment by tthvo** [comment]
Right, I would just remove secrets instead of adding ConfigMap as it could means unprotected data which is not the case for certificates and credentials.

**Comment by tthvo** [comment]
I found some `ConfigMap` that actually contains certificate data. I think in the case of certificates, we could use `ConfigMap`?
```bash
oc get cm
NAME                       DATA   AGE
auth-properties            1      24h
kube-root-ca.crt           1      65d
openshift-service-ca.crt   1      65d
```

**Comment by ebaron** [comment]
> I found some `ConfigMap` that actually contains certificate data. I think in the case of certificates, we could use `ConfigMap`?

I don't think we gain much from doing that. Certificates can be stored in Config Maps because they aren't sensitive, but for Cryostat, the certificate permission allows the user to tell Cryostat to trust a certificate. This should be somewhat of a privileged action, and I don't think creating/updating config maps in the namespace captures it. Permission to create/update the Cryostat CR is better, because that captures more of an admin role.

**Comment by tthvo** [comment]
Oh right! Make sense! Thanks a lot for explaining! I will finish up features to add custom role on top of default and clean up tests before marking this ready,

**Comment by ebaron** [comment]
Thanks, once this is ready, I'll test this one along with the operator PR and we should (hopefully) be done.

**Review by ebaron — APPROVED** [review]
Works well for me!
