### PR TITLE
fix(api): set Content-Type header on all responses

### LINKED ISSUE #586: API responses should contain Content-Type headers

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #586

### CODE REVIEW

File: src/test/java/io/cryostat/net/web/http/api/v1/TargetsGetHandlerTest.java [hunk 1]
```diff
@@ -131,5 +135,6 @@ public JMXServiceURL answer(InvocationOnMock args) throws Throwable {
                 gson.fromJson(
                         responseCaptor.getValue(), new TypeToken<List<ServiceRef>>() {}.getType());
         MatcherAssert.assertThat(result, Matchers.equalTo(targets));
+        Mockito.verify(resp).putHeader(HttpHeaders.CONTENT_TYPE, "application/json");
```
Comment (jan-law) [inline src/test/java/io/cryostat/net/web/http/api/v1/TargetsGetHandlerTest.java:138]: I noticed only some tests call `verify(resp).putHeader()`. When is it appropriate to `verify()` that `putHeader()` was called?

Comment (andrewazores) [reply src/test/java/io/cryostat/net/web/http/api/v1/TargetsGetHandlerTest.java:138]: For V1 handlers, the behaviour is split between two places - for non-default values it's done by the specific implementation, otherwise it's done by the parent `AbstractAuthenticatedRequestHandler` in a different method. Since V1 tests generally directly invoke the `handleAuthenticated` method the default behaviour provided by the abstract parent class is not executed, so the test doesn't check for it either.

I should add a test that the parent class does do this default behaviour, though.

**Review by hareetd — DISMISSED** [review]
