### PR TITLE
fix(diagnostics): support bucket metadata mode

### LINKED ISSUE #1168: [Bug] Bucket metadata mode doesn't work with diagnostics features
### Current Behavior

Caused by a missing implementation of the metadata service

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```Markdown
- OS:
- Environment:
- Version:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Josh-Matsuoka**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [ ] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [ ] Linked a relevant issue which this PR resolves
* [ ] Linked any other relevant issues, PR's, or documentation, if any
* [ ] Resolved all conflicts, if any
* [ ] Rebased your branch PR on top of the latest upstream `main` branch
* [ ] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [ ] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: [#<issue number>](https://github.com/cryostatio/cryostat/issues/1168)

## Description of the change:
Adds the missing implementation of the diagnostics metadata services to resolve #1168 

## Motivation for the change:
*This change is helpful because users may want to...*

## How to manually test:
- Set up a cryostat instance to point at an external storage provider, set the metadata mode to bucket
- Test the diagnostics features, make sure thread and heap dumps can be stored, check that label editing works

### CODE REVIEW

File: src/main/java/io/cryostat/diagnostic/BucketedThreadDumpsMetadataService.java [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+        name = ConfigProperties.STORAGE_METADATA_STORAGE_MODE,
+        stringValue = ThreadDumpsMetadataService.METADATA_STORAGE_MODE_BUCKET)
+/**
+ * Implements diagnostics metadata as standalone objects in a bucket. When the storage mode is set
+ * to select this implementation, diagnostics metadata is not stored using the S3 object Tags, but
+ * rather as separate JSON files in separate buckets. This ensures broader compatibility with
+ * different S3-like implementations and providers, and also circumvents any limitations on tag
+ * count or tag size/length.
+ */
+class BucketedDiagnosticsMetadataService implements ThreadDumpsMetadataService {
```
Comment (andrewazores) [inline src/main/java/io/cryostat/diagnostic/BucketedThreadDumpsMetadataService.java]: Class name doesn't match file name

File: src/main/resources/application.properties
Comment (andrewazores) [inline src/main/resources/application.properties]: https://github.com/cryostatio/cryostat/blob/902c59e43b8432a9d6380e358b73ce8af2c41195/src/main/resources/application.properties#L133

I think there should also be lines added here to set the storage mode for heap/thread dumps?

**Review by andrewazores — APPROVED** [review]

**Review by andrewazores — APPROVED** [review]
