### PR TITLE
fix(auto-rules): Check for null json before creating rule

### LINKED ISSUE #570: Posting empty JSON rule returns HTTP 500
Adding a new rule without a JSON object and `Content-Type: application/json` results in an `HTTP 500` error. The error should be handled or thrown as an `HTTP 400` error.

```
$ curl --insecure -X POST -H "Content-Type: application/json" https://0.0.0.0:8181/api/v2/rules/

{"meta":{"type":"text/plain","status":"Internal Server Error"},"data":{"reason":null}}
```

### PR DESCRIPTION
**Pull request by jan-law**
Fixes #570

Cause of the error is from `RulesPostHandler line 130`:
- `gson.fromJson` returns `null` without throwing an exception
- `null` is passed to `addRule()` which throws an `IOException`/`500`
```
public <T> T fromJson(String json, Type typeOfT) throws JsonSyntaxException {
    if (json == null) {
      return null;
    }
    StringReader reader = new StringReader(json);
    T target = (T) fromJson(reader, typeOfT);
    return target;
  }

### CODE REVIEW

File: src/main/java/io/cryostat/net/web/http/api/v2/RulesPostHandler.java [hunk 1]
```diff
@@ -127,6 +127,10 @@ public boolean isOrdered() {
             case JSON:
                 try {
                     rule = gson.fromJson(params.getBody(), Rule.class);
+
+                    if (rule == null) {
+                        throw new IllegalArgumentException("No JSON found");
```
Comment (andrewazores) [inline src/main/java/io/cryostat/net/web/http/api/v2/RulesPostHandler.java:132]: I think the message here could be a little more precise. Something like `POST body was null`, that indicates exactly to the user/client what their mistake was.

**Review by andrewazores — APPROVED** [review]

**Comment by andrewazores** [comment]
@jan-law could you rebase this? I'll re-approve and merge it after.

**Comment by jan-law** [comment]
Thanks for the reminder, rebased now.

**Review by andrewazores — APPROVED** [review]
