### PR TITLE
fix(discovery): retry failed target connections

### LINKED ISSUE #1577: [Bug] JVM target discovery failure when pod restarts
Hi team, 
I am trying to connect TechEmpower Quarkus application with Cryostat to collect JDK Flight recordings.
I have configured the Quarkus application using JMX with below configuration:

JVM flags:
```
-Dcom.sun.management.jmxremote.port=9091
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.authenticate=false
```

pod specs:
```yaml
containers:
  - name: tfb-server
    image: 'quay.io/shbirada/tfb-qrh:1.13.2.F_et17'
    imagePullPolicy: IfNotPresent
    env:
      - name: JAVA_OPTIONS
        value: >-
          -server
          -Dcom.sun.management.jmxremote.port=9091
          -Dcom.sun.management.jmxremote.ssl=false
          -Dcom.sun.management.jmxremote.authenticate=false
    ports:
      - containerPort: 8080
```
service specs:
```yaml
 ports:
  - port: 8080
    targetPort: 8080
    name: tfb-qrh-port
  - port: 9091
    targetPort: 9091
    name: jfr-jmx
```

Whenever the pod restarts the Cryostat Client fails to discover the JVM target . I have tried deleting the existing deployment and re-deploying the quarkus yaml file multiple times but nothing seems to be working.

Cryostat pod description:
```
Events:
  Type    Reason          Age   From               Message
  ----    ------          ----  ----               -------
  Normal  Scheduled       81m   default-scheduler  Successfully assigned tfb/cryostat-tfb1-76b5f684bf-r2dz6 to worker-2.tfbcluster.lab.upshift.rdu2.redhat.com
  Normal  AddedInterface  81m   multus             Add eth0 [10.128.3.110/23] from ovn-kubernetes
  Normal  Pulled          81m   kubelet            Container image "registry.redhat.io/cryostat-tech-preview/cryostat-rhel8@sha256:5a58a0f654f321bdfc91bee2dfaffb43bc018a2007dc5123029053e3b09d5d18" already present on machine
  Normal  Created         81m   kubelet            Created container cryostat-tfb1
  Normal  Started         81m   kubelet            Started container cryostat-tfb1
  Normal  Pulled          81m   kubelet            Container image "registry.redhat.io/cryostat-tech-preview/cryostat-grafana-dashboard-rhel8@sha256:c85e96b2a13c44efa6e595ac3ece194b178fc839de5acc6b17375ad8821a5f5d" already present on machine
  Normal  Created         81m   kubelet            Created container cryostat-tfb1-grafana
  Normal  Started         81m   kubelet            Started container cryostat-tfb1-grafana
  Normal  Pulled          81m   kubelet            Container image "registry.redhat.io/cryostat-tech-preview/jfr-datasource-rhel8@sha256:2b6cb93a32fd7290ea6f49da11a54ee6e5d3f50e87ee1ea56eb54419fc3a1671" already present on machine
  Normal  Created         81m   kubelet            Created container cryostat-tfb1-jfr-datasource
  Normal  Started         81m   kubelet            Started container cryostat-tfb1-jfr-datasource
```
Cryostat pod logs Authentication error, but I am able to access the Cryostat Dashboard using the same credentials from Red Hat OpenShift Platform.

```
Defaulted container "cryostat-tfb1" out of: cryostat-tfb1, cryostat-tfb1-grafana, cryostat-tfb1-jfr-datasource
Importing certificate /truststore/operator/..2023_07_05_08_57_56.1003949320/cryostat-tfb1-ca.crt ...
Certificate was added to keystore
[Storing /opt/cryostat.d/truststore.p12]
+ exec java -XX:+CrashOnOutOfMemoryError -Dcom.sun.management.jmxremote.port=9091 -Dcom.sun.management.jmxremote.rmi.port=9091 -Djavax.net.ssl.trustStore=/opt/cryostat.d/truststore.p12 -Djavax.net.ssl.trustStorePassword=t-4tT7JpyeG1MHB9szlQY7I3rNaGZJr9 -Dcom.sun.management.jmxremote.autodiscovery=false -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.password.file=/tmp/jmxremote.password -Dcom.sun.management.jmxremote.access.file=/tmp/jmxremote.access -Dcom.sun.management.jmxremote.ssl.need.client.auth=true -Djavax.net.ssl.keyStore=/var/run/secrets/operator.cryostat.io/cryostat-tfb1-tls/keystore.p12 -Djavax.net.ssl.keyStorePassword=nXDjdGLUsjHWK9F4jAVl -Dcom.sun.management.jmxremote.ssl=true -Dcom.sun.management.jmxremote.registry.ssl=true -cp '/app/resources:/app/classes:/app/libs/*:/opt/cryostat.d/clientlib.d/*' @/app/jib-main-class-file
Jul 05, 2023 8:57:58 AM io.cryostat.core.log.Logger info
INFO: Local config path set as /opt/cryostat.d/conf.d
Jul 05, 2023 8:57:58 AM org.hibernate.jpa.internal.util.LogHelper logPersistenceUnitInformation
INFO: HHH000204: Processing PersistenceUnitInfo [name: io.cryostat]
Jul 05, 2023 8:57:58 AM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate ORM core version 5.6.14.Final-redhat-00001
Jul 05, 2023 8:57:58 AM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.1.2.Final-redhat-00005}
Jul 05, 2023 8:57:59 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
WARN: HHH10001002: Using Hibernate built-in connection pool (not for production use!)
Jul 05, 2023 8:57:59 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH10001005: using driver [org.h2.Driver] at URL [jdbc:h2:file:/opt/cryostat.d/conf.d/h2;INIT=create domain if not exists jsonb as varchar]
Jul 05, 2023 8:57:59 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH10001001: Connection properties: {password=****, user=cryostat-tfb1}
Jul 05, 2023 8:57:59 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH10001003: Autocommit mode: false
Jul 05, 2023 8:57:59 AM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections <init>
INFO: HHH000115: Hibernate connection pool size: 20 (min=1)
Jul 05, 2023 8:57:59 AM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Jul 05, 2023 8:57:59 AM org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl getIsolatedConnection
INFO: HHH10001501: Connection obtained from JdbcConnectionAccess [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess@63d2b4a6] for (non-JTA) DDL execution was not in auto-commit mode; the Connection 'local transaction' will be committed and the Connection will be set into auto-commit mode.
Jul 05, 2023 8:57:59 AM org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator initiateService
INFO: HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: cryostat started, version: 2.3.0.redhat-00004-0-g47f9627.
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Selected SSL KeyStore strategy with keystore /var/run/secrets/operator.cryostat.io/cryostat-tfb1-tls/keystore.p12
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deploying io.cryostat.net.HttpServer Verticle with options: {
  "ha" : false,
  "instances" : 1,
  "maxWorkerExecuteTime" : 60000000000,
  "maxWorkerExecuteTimeUnit" : "NANOSECONDS",
  "worker" : false,
  "workerPoolSize" : 20
}
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: HTTPS service running on https://cryostat-tfb1-tfb.apps.tfbcluster.lab.upshift.rdu2.redhat.com:443
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deployed io.cryostat.net.HttpServer Verticle [e159c5aa-785c-42bf-b4f2-2f39feb86806]
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Selecting configured AuthManager "io.cryostat.net.openshift.OpenShiftAuthManager"
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Local save path for flight recordings set as /opt/cryostat.d/recordings.d
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deploying io.cryostat.net.web.WebServer Verticle with options: {
  "ha" : false,
  "instances" : 1,
  "maxWorkerExecuteTime" : 60000000000,
  "maxWorkerExecuteTimeUnit" : "NANOSECONDS",
  "worker" : false,
  "workerPoolSize" : 20
}
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deployed io.cryostat.net.web.WebServer Verticle [470d4349-5276-430e-b7f9-540a35658339]
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deploying io.cryostat.messaging.MessagingServer Verticle with options: {
  "ha" : false,
  "instances" : 1,
  "maxWorkerExecuteTime" : 60000000000,
  "maxWorkerExecuteTimeUnit" : "NANOSECONDS",
  "worker" : false,
  "workerPoolSize" : 20
}
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Max concurrent WebSocket connections: 2147483647
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deployed io.cryostat.messaging.MessagingServer Verticle [fb282490-038c-4865-aa1c-27a3d576db35]
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deploying io.cryostat.rules.RuleProcessor Verticle with options: {
  "ha" : false,
  "instances" : 1,
  "maxWorkerExecuteTime" : 60000000000,
  "maxWorkerExecuteTimeUnit" : "NANOSECONDS",
  "worker" : true,
  "workerPoolName" : "io.cryostat.rules.RuleProcessor-worker",
  "workerPoolSize" : 20
}
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deployed io.cryostat.rules.RuleProcessor Verticle [a9d5202f-ae4e-4f2b-8781-e7f29d2dc29c]
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deploying io.cryostat.recordings.RecordingMetadataManager Verticle with options: {
  "ha" : false,
  "instances" : 1,
  "maxWorkerExecuteTime" : 60000000000,
  "maxWorkerExecuteTimeUnit" : "NANOSECONDS",
  "worker" : true,
  "workerPoolName" : "io.cryostat.recordings.RecordingMetadataManager-worker",
  "workerPoolSize" : 20
}
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Peeking contents of metadata directory: lost
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Skipping metadata validation: appears to be a special location: lost
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Peeking contents of metadata directory: I5KFG33XNFAWGNSOL5YFK4LNPJBFSTTPGJZVO2BSM5EUCMBSNUZWOWSRKEYWSZSOGNRXOPI=
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deleting empty recording metadata directory: /opt/cryostat.d/conf.d/metadata/I5KFG33XNFAWGNSOL5YFK4LNPJBFSTTPGJZVO2BSM5EUCMBSNUZWOWSRKEYWSZSOGNRXOPI=
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deployed io.cryostat.recordings.RecordingMetadataManager Verticle [beb23067-760a-419e-b904-c74989a86106]
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deploying io.cryostat.discovery.DiscoveryStorage Verticle with options: {
  "ha" : false,
  "instances" : 1,
  "maxWorkerExecuteTime" : 60000000000,
  "maxWorkerExecuteTimeUnit" : "NANOSECONDS",
  "worker" : true,
  "workerPoolName" : "io.cryostat.discovery.DiscoveryStorage-worker",
  "workerPoolSize" : 20
}
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Deploying io.cryostat.discovery.BuiltInDiscovery Verticle with options: {
  "ha" : false,
  "instances" : 1,
  "maxWorkerExecuteTime" : 60000000000,
  "maxWorkerExecuteTimeUnit" : "NANOSECONDS",
  "worker" : true,
  "workerPoolName" : "io.cryostat.discovery.BuiltInDiscovery-worker",
  "workerPoolSize" : 20
}
Jul 05, 2023 8:58:00 AM io.cryostat.core.log.Logger info
INFO: Selected KubeApiPlatformStrategy Strategy
Jul 05, 2023 8:58:01 AM io.cryostat.core.log.Logger info
INFO: Started Endpoints SharedInformer for namespace "tfb"
Jul 05, 2023 8:58:01 AM io.cryostat.core.log.Logger info
INFO: Selected PodmanPlatformStrategy Strategy
Jul 05, 2023 8:58:01 AM io.cryostat.core.log.Logger info
INFO: Selected Default Platform Strategy
Jul 05, 2023 8:58:01 AM io.cryostat.core.log.Logger info
INFO: Starting built-in discovery with CustomTargetPlatformClient
Jul 05, 2023 8:58:01 AM io.cryostat.core.log.Logger info
INFO: Selected OpenShiftPlatformStrategy Strategy
Jul 05, 2023 8:58:01 AM io.cryostat.core.log.Logger info
INFO: Starting built-in discovery with KubeApiPlatformClient
Jul 05, 2023 8:58:02 AM io.cryostat.core.log.Logger info
INFO: Started Endpoints SharedInformer for namespace "tfb"
Jul 05, 2023 8:58:02 AM io.cryostat.core.log.Logger info
INFO: Observing new target: io.cryostat.platform.ServiceRef@6fc52ffd[alias=tfb-qrh-sample-7bc8684948-frjwz,annotations=io.cryostat.platform.ServiceRef$Annotations@7eb699c1[cryostat={HOST=10.128.3.97, PORT=9091, NAMESPACE=tfb, POD_NAME=tfb-qrh-sample-7bc8684948-frjwz, REALM=KubernetesApi},platform={openshift.io/scc=restricted-v2, seccomp.security.alpha.kubernetes.io/pod=runtime/default, k8s.ovn.org/pod-networks={"default":{"ip_addresses":["10.128.3.97/23"],"mac_address":"0a:58:0a:80:03:61","gateway_ips":["10.128.2.1"],"ip_address":"10.128.3.97/23","gateway_ip":"10.128.2.1"}}, k8s.v1.cni.cncf.io/network-status=[{
    "name": "ovn-kubernetes",
    "interface": "eth0",
    "ips": [
        "10.128.3.97"
    ],
    "mac": "0a:58:0a:80:03:61",
    "default": true,
    "dns": {}
}]}],jvmId=<null>,labels={app=tfb-qrh-deployment, app.kubernetes.io/name=tfb-qrh-deployment, name=tfb-qrh-deployment, pod-template-hash=7bc8684948, version=v1, app.kubernetes.io/layer=quarkus},serviceUri=service:jmx:rmi:///jndi/rmi://10-128-3-97.tfb.pod:9091/jmxrmi]
Jul 05, 2023 8:58:02 AM io.cryostat.core.log.Logger info
INFO: Creating connection for service:jmx:rmi:///jndi/rmi://10-128-3-97.tfb.pod:9091/jmxrmi
Jul 05, 2023 8:58:04 AM io.cryostat.core.log.Logger info
INFO: Deployed io.cryostat.discovery.BuiltInDiscovery Verticle [1315954f-b235-4b27-a4e8-3a1b90a2130e]
Jul 05, 2023 8:58:04 AM io.cryostat.core.log.Logger info
INFO: Deployed io.cryostat.discovery.DiscoveryStorage Verticle [f1f85698-8dc7-45e6-af87-c6904cd98690]
Jul 05, 2023 8:58:04 AM io.cryostat.core.log.Logger info
INFO: Outgoing WS message: {"meta":{"category":"TargetJvmDiscovery","type":{"type":"application","subType":"json"},"serverTime":1688547481},"message":{"event":{"serviceRef":{"jvmId":null,"connectUrl":"service:jmx:rmi:///jndi/rmi://10-131-0-25.tfb.pod:9091/jmxrmi","alias":"cryostat-tfb1-76b5f684bf-m2chk","labels":{"app":"cryostat-tfb1","pod-template-hash":"76b5f684bf","component":"cryostat","kind":"cryostat"},"annotations":{"platform":{"seccomp.security.alpha.kubernetes.io/pod":"runtime/default","openshift.io/scc":"restricted-v2","k8s.ovn.org/pod-networks":"{\"default\":{\"ip_addresses\":[\"10.131.0.25/23\"],\"mac_address\":\"0a:58:0a:83:00:19\",\"gateway_ips\":[\"10.131.0.1\"],\"ip_address\":\"10.131.0.25/23\",\"gateway_ip\":\"10.131.0.1\"}}","k8s.v1.cni.cncf.io/network-status":"[{\n    \"name\": \"ovn-kubernetes\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.131.0.25\"\n    ],\n    \"mac\": \"0a:58:0a:83:00:19\",\n    \"default\": true,\n    \"dns\": {}\n}]"},"cryostat":{"HOST":"10.131.0.25","PORT":"9091","NAMESPACE":"tfb","POD_NAME":"cryostat-tfb1-76b5f684bf-m2chk","REALM":"KubernetesApi"}}},"kind":"LOST"}}}
Jul 05, 2023 8:58:04 AM io.cryostat.core.log.Logger info
INFO: Outgoing WS message: {"meta":{"category":"TargetJvmDiscovery","type":{"type":"application","subType":"json"},"serverTime":1688547484},"message":{"event":{"serviceRef":{"jvmId":"Ae7TI2hyS81CE8zxQ4SU_mivHizT18XpON68sV1wwZQ=","connectUrl":"service:jmx:rmi:///jndi/rmi://10-128-3-97.tfb.pod:9091/jmxrmi","alias":"tfb-qrh-sample-7bc8684948-frjwz","labels":{"app":"tfb-qrh-deployment","app.kubernetes.io/name":"tfb-qrh-deployment","name":"tfb-qrh-deployment","pod-template-hash":"7bc8684948","version":"v1","app.kubernetes.io/layer":"quarkus"},"annotations":{"platform":{"seccomp.security.alpha.kubernetes.io/pod":"runtime/default","openshift.io/scc":"restricted-v2","k8s.ovn.org/pod-networks":"{\"default\":{\"ip_addresses\":[\"10.128.3.97/23\"],\"mac_address\":\"0a:58:0a:80:03:61\",\"gateway_ips\":[\"10.128.2.1\"],\"ip_address\":\"10.128.3.97/23\",\"gateway_ip\":\"10.128.2.1\"}}","k8s.v1.cni.cncf.io/network-status":"[{\n    \"name\": \"ovn-kubernetes\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.128.3.97\"\n    ],\n    \"mac\": \"0a:58:0a:80:03:61\",\n    \"default\": true,\n    \"dns\": {}\n}]"},"cryostat":{"HOST":"10.128.3.97","PORT":"9091","NAMESPACE":"tfb","POD_NAME":"tfb-qrh-sample-7bc8684948-frjwz","REALM":"KubernetesApi"}}},"kind":"FOUND"}}}
Jul 05, 2023 8:58:04 AM io.cryostat.core.log.Logger info
INFO: Starting archive migration
Jul 05, 2023 8:58:04 AM io.cryostat.core.log.Logger info
INFO: Skipping archive migration: appears to be a special location: file-uploads
Jul 05, 2023 8:58:04 AM io.cryostat.core.log.Logger info
INFO: Skipping archive migration: appears to be a special location: lost
Jul 05, 2023 8:58:04 AM io.cryostat.core.log.Logger info
INFO: Successfully migrated archives
Jul 05, 2023 8:58:04 AM io.cryostat.core.log.Logger info
INFO: Beginning to prune potentially stale metadata...
Jul 05, 2023 8:58:04 AM io.cryostat.core.log.Logger info
INFO: Successfully pruned all stale metadata
Jul 05, 2023 8:58:04 AM io.cryostat.core.log.Logger info
INFO: JVM ID: service:jmx:rmi:///jndi/rmi://10-128-3-97.tfb.pod:9091/jmxrmi -> Ae7TI2hyS81CE8zxQ4SU_mivHizT18XpON68sV1wwZQ=
Jul 05, 2023 8:58:06 AM org.slf4j.impl.JDK14LoggerAdapter fillCallerData
INFO: 10.128.2.2 - - [Wed, 5 Jul 2023 08:58:06 GMT] 3ms "GET /health/liveness HTTP/1.1" 204 0 bytes "-" "kube-probe/1.26"
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger info
INFO: Observing new target: io.cryostat.platform.ServiceRef@7f6feb45[alias=cryostat-tfb1-76b5f684bf-r2dz6,annotations=io.cryostat.platform.ServiceRef$Annotations@71a80ad8[cryostat={HOST=10.128.3.110, PORT=9091, NAMESPACE=tfb, POD_NAME=cryostat-tfb1-76b5f684bf-r2dz6, REALM=KubernetesApi},platform={openshift.io/scc=restricted-v2, seccomp.security.alpha.kubernetes.io/pod=runtime/default, k8s.ovn.org/pod-networks={"default":{"ip_addresses":["10.128.3.110/23"],"mac_address":"0a:58:0a:80:03:6e","gateway_ips":["10.128.2.1"],"ip_address":"10.128.3.110/23","gateway_ip":"10.128.2.1"}}, k8s.v1.cni.cncf.io/network-status=[{
    "name": "ovn-kubernetes",
    "interface": "eth0",
    "ips": [
        "10.128.3.110"
    ],
    "mac": "0a:58:0a:80:03:6e",
    "default": true,
    "dns": {}
}]}],jvmId=<null>,labels={app=cryostat-tfb1, pod-template-hash=76b5f684bf, component=cryostat, kind=cryostat},serviceUri=service:jmx:rmi:///jndi/rmi://10-128-3-110.tfb.pod:9091/jmxrmi]
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger info
INFO: Creating connection for service:jmx:rmi:///jndi/rmi://10-128-3-110.tfb.pod:9091/jmxrmi
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger info
INFO: connection attempt failed.
 
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger info
INFO: Connection for service:jmx:rmi:///jndi/rmi://10-128-3-110.tfb.pod:9091/jmxrmi closed
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger error
SEVERE: Exception thrown
org.openjdk.jmc.rjmx.ConnectionException caused by java.lang.SecurityException: Authentication failed! Invalid username or password
        at org.openjdk.jmc.rjmx.internal.RJMXConnection.connect(RJMXConnection.java:345)
        at io.cryostat.core.net.JFRJMXConnection.attemptConnect(JFRJMXConnection.java:443)
        at io.cryostat.core.net.JFRJMXConnection.connect(JFRJMXConnection.java:399)
        at io.cryostat.core.net.JFRJMXConnection.getJvmId(JFRJMXConnection.java:204)
        at io.cryostat.net.TargetConnectionManager.lambda$executeConnectedTaskAsync$2(TargetConnectionManager.java:153)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.SecurityException: Authentication failed! Invalid username or password
        at java.management/com.sun.jmx.remote.security.JMXPluggableAuthenticator.authenticationFailure(JMXPluggableAuthenticator.java:231)
        at java.management/com.sun.jmx.remote.security.JMXPluggableAuthenticator.authenticate(JMXPluggableAuthenticator.java:208)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap$AccessFileCheckerAuthenticator.authenticate(ConnectorBootstrap.java:233)
        at java.management.rmi/javax.management.remote.rmi.RMIServerImpl.doNewClient(RMIServerImpl.java:231)
        at java.management.rmi/javax.management.remote.rmi.RMIServerImpl.newClient(RMIServerImpl.java:198)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:304)
        at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:280)
        at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:165)
        at java.management.rmi/javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83)
        at java.management.rmi/javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2107)
        at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321)
        at org.openjdk.jmc.rjmx.internal.RJMXConnection.connectJmxConnector(RJMXConnection.java:575)
        at org.openjdk.jmc.rjmx.internal.RJMXConnection.establishConnection(RJMXConnection.java:560)
        at org.openjdk.jmc.rjmx.internal.RJMXConnection.connect(RJMXConnection.java:338)
        ... 11 more
Caused by: javax.security.auth.login.FailedLoginException: Invalid username or password
        at java.management/com.sun.jmx.remote.security.FileLoginModule.attemptAuthentication(FileLoginModule.java:460)
        at java.management/com.sun.jmx.remote.security.FileLoginModule.login(FileLoginModule.java:309)
        at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:679)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:677)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:677)
        at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at java.management/com.sun.jmx.remote.security.JMXPluggableAuthenticator.authenticate(JMXPluggableAuthenticator.java:195)
        at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap$AccessFileCheckerAuthenticator.authenticate(ConnectorBootstrap.java:233)
        at java.management.rmi/javax.management.remote.rmi.RMIServerImpl.doNewClient(RMIServerImpl.java:231)
        at java.management.rmi/javax.management.remote.rmi.RMIServerImpl.newClient(RMIServerImpl.java:198)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
 
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger info
INFO: Removing cached connection for service:jmx:rmi:///jndi/rmi://10-128-3-110.tfb.pod:9091/jmxrmi: EXPLICIT
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger warn
WARNING: Could not resolve jvmId for target service:jmx:rmi:///jndi/rmi://10-128-3-110.tfb.pod:9091/jmxrmi
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger info
INFO: Update node [service:jmx:rmi:///jndi/rmi://10-128-3-110.tfb.pod:9091/jmxrmi] with null jvmId
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger info
INFO: Observing new target: io.cryostat.platform.ServiceRef@36c74ad2[alias=tfb-qrh-sample-7bc8684948-frjwz,annotations=io.cryostat.platform.ServiceRef$Annotations@410b26b1[cryostat={HOST=10.128.3.97, PORT=9091, NAMESPACE=tfb, POD_NAME=tfb-qrh-sample-7bc8684948-frjwz, REALM=KubernetesApi},platform={openshift.io/scc=restricted-v2, seccomp.security.alpha.kubernetes.io/pod=runtime/default, k8s.ovn.org/pod-networks={"default":{"ip_addresses":["10.128.3.97/23"],"mac_address":"0a:58:0a:80:03:61","gateway_ips":["10.128.2.1"],"ip_address":"10.128.3.97/23","gateway_ip":"10.128.2.1"}}, k8s.v1.cni.cncf.io/network-status=[{
    "name": "ovn-kubernetes",
    "interface": "eth0",
    "ips": [
        "10.128.3.97"
    ],
    "mac": "0a:58:0a:80:03:61",
    "default": true,
    "dns": {}
}]}],jvmId=<null>,labels={app=tfb-qrh-deployment, app.kubernetes.io/name=tfb-qrh-deployment, name=tfb-qrh-deployment, pod-template-hash=7bc8684948, version=v1, app.kubernetes.io/layer=quarkus},serviceUri=service:jmx:rmi:///jndi/rmi://10-128-3-97.tfb.pod:9091/jmxrmi]
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger info
INFO: Outgoing WS message: {"meta":{"category":"TargetJvmDiscovery","type":{"type":"application","subType":"json"},"serverTime":1688547487},"message":{"event":{"serviceRef":{"jvmId":null,"connectUrl":"service:jmx:rmi:///jndi/rmi://10-128-3-110.tfb.pod:9091/jmxrmi","alias":"cryostat-tfb1-76b5f684bf-r2dz6","labels":{"app":"cryostat-tfb1","pod-template-hash":"76b5f684bf","component":"cryostat","kind":"cryostat"},"annotations":{"platform":{"seccomp.security.alpha.kubernetes.io/pod":"runtime/default","openshift.io/scc":"restricted-v2","k8s.ovn.org/pod-networks":"{\"default\":{\"ip_addresses\":[\"10.128.3.110/23\"],\"mac_address\":\"0a:58:0a:80:03:6e\",\"gateway_ips\":[\"10.128.2.1\"],\"ip_address\":\"10.128.3.110/23\",\"gateway_ip\":\"10.128.2.1\"}}","k8s.v1.cni.cncf.io/network-status":"[{\n    \"name\": \"ovn-kubernetes\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.128.3.110\"\n    ],\n    \"mac\": \"0a:58:0a:80:03:6e\",\n    \"default\": true,\n    \"dns\": {}\n}]"},"cryostat":{"HOST":"10.128.3.110","PORT":"9091","NAMESPACE":"tfb","POD_NAME":"cryostat-tfb1-76b5f684bf-r2dz6","REALM":"KubernetesApi"}}},"kind":"FOUND"}}}
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger info
INFO: Creating connection for service:jmx:rmi:///jndi/rmi://10-128-3-110.tfb.pod:9091/jmxrmi
Jul 05, 2023 8:58:07 AM io.cryostat.core.log.Logger info
INFO: connection attempt failed.
INFO: Outgoing WS message: {"meta":{"category":"WsClientActivity","type":{"type":"application","subType":"json"},"serverTime":1688547806},"message":{"10.128.2.2:35666":"accepted"}}
Jul 05, 2023 9:03:27 AM org.slf4j.impl.JDK14LoggerAdapter fillCallerData
INFO: 10.128.2.2 - - [Wed, 5 Jul 2023 09:03:27 GMT] 79ms "GET /api/v1/recordings HTTP/1.1" 200 9 KB "https://cryostat-tfb1-tfb.apps.tfbcluster.lab.upshift.rdu2.redhat.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
Jul 05, 2023 9:03:36 AM org.slf4j.impl.JDK14LoggerAdapter fillCallerData
INFO: 10.128.2.2 - - [Wed, 5 Jul 2023 09:03:36 GMT] 0ms "GET /health/liveness HTTP/1.1" 204 0 bytes "-" "kube-probe/1.26"
Jul 05, 2023 9:03:46 AM org.slf4j.impl.JDK14LoggerAdapter fillCallerData
INFO: 10.128.2.2 - - [Wed, 5 Jul 2023 09:03:46 GMT] 0ms "GET /health/liveness HTTP/1.1" 204 0 bytes "-" "kube-probe/1.26"
Jul 05, 2023 9:03:56 AM org.slf4j.impl.JDK14LoggerAdapter fillCallerData
INFO: 10.128.2.2 - - [Wed, 5 Jul 2023 09:03:56 GMT] 0ms "GET /health/liveness HTTP/1.1" 204 0 bytes "-" "kube-probe/1.26"

```   

Cryostat target is detected but JVM target option cannot be seen
Cryostat-target

Topology dashboard:
topology

## Environment:
- OS: RHEL 8.8
- Environment: OpenShift 4.13.1
- Version: 2.3.0
- Java: OpenJDK version "17.0.6"

### PR DESCRIPTION
**Pull request by andrewazores**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [x] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [x] Linked a relevant issue which this PR resolves
* [x] Linked any other relevant issues, PR's, or documentation, if any
* [x] Resolved all conflicts, if any
* [x] Rebased your branch PR on top of the latest upstream `main` branch
* [x] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [x] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes #1577

### CODE REVIEW

File: src/main/java/io/cryostat/discovery/DiscoveryStorage.java [hunk 1]
```diff
@@ -143,34 +147,53 @@ public void start(Promise<Void> future) throws Exception {
                                                                                 + " deployed")))
                 .onFailure(future::fail);
 
-        this.timerId = getVertx().setPeriodic(pingPeriod.toMillis(), i -> pingPrune());
+        this.pluginPruneTimerId = getVertx().setPeriodic(pingPeriod.toMillis(), i -> pingPrune());
+        this.targetRetryTimeId =
+                getVertx()
+                        .setPeriodic(
+                                // TODO make this configurable, use an exponential backoff, have a
+                                // maximum retry policy, etc.
```
Comment (tthvo) [inline src/main/java/io/cryostat/discovery/DiscoveryStorage.java:155]: Are we planning these configurations for this PR?

Comment (andrewazores) [reply src/main/java/io/cryostat/discovery/DiscoveryStorage.java:155]: I thought about it, but I'm not sure it's worth investing the time/effort into it. This is a narrow enough corner case that a single retry after 15 seconds is almost certain to succeed, so the exponential backoff wouldn't do anything. Maximum retries could be useful but it would be something that the end user needs to decide to configure, which I doubt would happen. Similarly for changing the periodicity, I'm not sure anyone would actually bother tuning the parameter. If this case is run into very frequently then the better solution is probably not to tune this parameter but instead to switch to using the Agent.

Comment (tthvo) [reply src/main/java/io/cryostat/discovery/DiscoveryStorage.java:155]: Ahh right! Sounds good! Thanks!

File: smoketest.sh [hunk 2]
```diff
@@ -116,6 +116,17 @@ runDemoApps() {
...
 
+    podman run \
+        --name vertx-fib-demo-0 \
+        --env HTTP_PORT=8079 \
+        --env JMX_PORT=9089 \
+        --env START_DELAY=60 \
+        --pod cryostat-pod \
+        --label io.cryostat.discovery="true" \
+        --label io.cryostat.jmxHost="localhost" \
+        --label io.cryostat.jmxPort="9093" \
```
Comment (tthvo) [inline smoketest.sh:127]: Should this be `9089` as set in `JMX_PORT=9089`?

**Review by tthvo — COMMENTED** [review]
Looks good! 

I tested with https://gist.github.com/tthvo/d8a2b727953b1c47b6b7095de658496b:

- The target appears but shows warning.
- Then sometime later, I can see the target is updated with a valid JVM ID.

Just kinda weird because the original issue was showing that Cryostat cannot see the target at all.

**Review by tthvo — APPROVED** [review]
