### PR TITLE
fix(k8s): replace Watch with Informer

### LINKED ISSUE #1036: [Task] k8s Endpoints watch can fail and remain disconnected
Hmm... I deployed cryostat operator with the latest images of `[cryostat]` and `[cryostat-web]` on Openshift through crc and followed the steps thereafter but I don't get the bug. Or at least, I get something different. When I restart the pod as I am on the CreateRecording tab, a "target appeared" notification never happens, however somehow cryostat is able to see the "new" target, see here
```
INFO: Creating connection for service:jmx:rmi:///jndi/rmi://10.217.0.122:9096/jmxrmi
Aug 02, 2022 10:05:08 PM io.cryostat.core.log.Logger info
INFO: (10.217.0.1:38650): GET /api/v1/targets/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2F10.217.0.122%3A9096%2Fjmxrmi/templates 200 75ms
Aug 02, 2022 10:05:08 PM io.cryostat.core.log.Logger info
INFO: (10.217.0.1:38652): GET /api/v1/targets/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2F10.217.0.122%3A9096%2Fjmxrmi/recordingOptions 200 95ms
Aug 02, 2022 10:05:14 PM io.cryostat.core.log.Logger info
INFO: Creating connection for service:jmx:rmi:///jndi/rmi://10.217.0.123:9096/jmxrmi
Aug 02, 2022 10:05:14 PM io.cryostat.core.log.Logger info
INFO: (10.217.0.111:48230): GET /api/v1/targets/10.217.0.123:9096/events 200 640ms
Aug 02, 2022 10:05:15 PM io.cryostat.core.log.Logger info
INFO: (10.217.0.111:48230): GET /api/v1/targets/10.217.0.123:9096/templates 200 63ms
```
where it just continues to GET from that target.
Similarly a "LOST" event never notifies either, but when I press the refresh targets button, it correctly doesn't show the target anymore.

_Originally posted by @maxcao13 in https://github.com/cryostatio/cryostat-web/issues/294#issuecomment-1203264993_

----

See continued discussion later in that issue's comments.

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #1036

update fabric8 kubernetes-client from 5.4.1 to 5.12.3 (latest 5.x) and replace direct Watch implementation with a fabric8 Informer. The Informer handles reconnecting the Watch on connection failures or when the API server responds with HTTP 410 (GONE), which can happen when too much time has elapsed between update notifications (such as during API server outages). The Informer also maintains an internal Store modelling the resource, in this case Endpoints, and resynchronizes this againt the API server periodically. This allows us to compute the list of ServiceRefs or the DiscoveryTree by constructing the result from the Informer's Store, rather than making an API call every time. Finally, the Informer's logic for added/updated/removed events is improved over the plain Watch and allows us to detect Pod scaling events correctly, as well as creation/deletion events.

For ease of testing, images are available at `quay.io/andrewazores/cryostat:k8s-rewatch-13` and `quay.io/andrewazores/cryostat-operator:k8s-rewatch-13`.

### CODE REVIEW

**Comment by tthvo** [comment]
> quay.io/andrewazores/cryostat-operator:k8s-rewatch.

@andrewazores  Any changes to the operator for this operator image?

**Comment by andrewazores** [comment]
I just built it with the `CORE_IMG` set. I think that still ends up regenerating some source files that go into the operator build, right? Otherwise no changes.

**Comment by maxcao13** [comment]
The endpoint watcher does restart now after being scheduled. 
```
INFO: Endpoints Watcher Exception. isShouldRetry: false, isHttpHone: true
Aug 04, 2022 9:46:58 PM io.cryostat.core.log.Logger error
SEVERE: Exception thrown
io.fabric8.kubernetes.client.WatcherException: too old resource version: 447684 (447994)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$TypedWatcherWebSocketListener.onMessage(WatchConnectionManager.java:103)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 447684 (447994)
	... 11 more

Aug 04, 2022 9:46:58 PM io.cryostat.core.log.Logger info
INFO: Starting kubernetes-client Endpoints watch in default
Aug 04, 2022 9:46:59 PM io.cryostat.core.log.Logger info
INFO: Outgoing WS message: {"meta":{"category":"TargetJvmDiscovery","type":{"type":"application","subType":"json"},"serverTime":1659649619},"message":{"event":{"serviceRef":{"connectUrl":"service:jmx:rmi:///jndi/rmi://10.217.0.100:9091/jmxrmi","alias":"cryostat-sample-588698ccc9-ppb46","labels":{"app":"cryostat-sample","pod-template-hash":"588698ccc9","component":"cryostat","kind":"cryostat"},"annotations":{"platform":{"k8s.v1.cni.cncf.io/networks-status":"[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.217.0.100\"\n    ],\n    \"default\": true,\n    \"dns\": {}\n}]","k8s.v1.cni.cncf.io/network-status":"[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.217.0.100\"\n    ],\n    \"default\": true,\n    \"dns\": {}\n}]"},"cryostat":{"HOST":"10.217.0.100","PORT":"9091","NAMESPACE":"default","POD_NAME":"cryostat-sample-588698ccc9-ppb46"}}},"kind":"FOUND"}}}
Aug 04, 2022 9:46:59 PM io.cryostat.core.log.Logger info
INFO: Outgoing WS message: {"meta":{"category":"TargetJvmDiscovery","type":{"type":"application","subType":"json"},"serverTime":1659649619},"message":{"event":{"serviceRef":{"connectUrl":"service:jmx:rmi:///jndi/rmi://10.217.0.14:9091/jmxrmi","alias":"vertx-fib-demo-84bbb76cdc-l4f5p","labels":{"pod-template-hash":"84bbb76cdc","deployment":"vertx-fib-demo"},"annotations":{"platform":{"k8s.v1.cni.cncf.io/networks-status":"[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.217.0.14\"\n    ],\n    \"default\": true,\n    \"dns\": {}\n}]","openshift.io/generated-by":"OpenShiftNewApp","k8s.v1.cni.cncf.io/network-status":"[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.217.0.14\"\n    ],\n    \"default\": true,\n    \"dns\": {}\n}]"},"cryostat":{"HOST":"10.217.0.14","PORT":"9091","NAMESPACE":"default","POD_NAME":"vertx-fib-demo-84bbb76cdc-l4f5p"}}},"kind":"FOUND"}}}
Aug 04, 2022 9:46:59 PM io.cryostat.core.log.Logger info
INFO: Outgoing WS message: {"meta":{"category":"TargetJvmDiscovery","type":{"type":"application","subType":"json"},"serverTime":1659649619},"message":{"event":{"serviceRef":{"connectUrl":"service:jmx:rmi:///jndi/rmi://10.217.0.28:9096/jmxrmi","alias":"quarkus-test-76bb776845-wmcll","labels":{"pod-template-hash":"76bb776845","deployment":"quarkus-test"},"annotations":{"platform":{"k8s.v1.cni.cncf.io/networks-status":"[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.217.0.28\"\n    ],\n    \"default\": true,\n    \"dns\": {}\n}]","openshift.io/generated-by":"OpenShiftNewApp","k8s.v1.cni.cncf.io/network-status":"[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.217.0.28\"\n    ],\n    \"default\": true,\n    \"dns\": {}\n}]"},"cryostat":{"HOST":"10.217.0.28","PORT":"9096","NAMESPACE":"default","POD_NAME":"quarkus-test-76bb776845-wmcll"}}},"kind":"FOUND"}}}
```

However, still after that no LOST notifications happen if I scale a Pod and I get the same bug as before.

Also, unrelated but this line in the logger
```
INFO: Endpoints Watcher Exception. isShouldRetry: false, isHttpHone: true
```
Not sure why `isHttpHone` is spelled `Hone` and not `Gone`, looks like a k8s internal thing.

**Comment by andrewazores** [comment]
> Not sure why isHttpHone is spelled Hone and not Gone, looks like a k8s internal thing.

Oh, my bad hahaha. The image tag I posted had that logger line in it but I removed it and force-pushed a new commit overtop, so you don't see it in the source anymore.

**Comment by andrewazores** [comment]
> However, still after that no LOST notifications happen if I scale a Pod and I get the same bug as before.

Hmm, I'll take another look. I didn't try scaling a Pod but I did test this with `make sample_app` and `make undeploy_sample_app` and observed the `LOST` notifications on undeploy as expected. Does that at least work for you?

**Comment by maxcao13** [comment]
> Hmm, I'll take another look. I didn't try scaling a Pod but I did test this with `make sample_app` and `make undeploy_sample_app` and observed the `LOST` notifications on undeploy as expected. Does that at least work for you?


It works! Seems like it doesn't detect `oc scale` scaling however. Also seems like the target dropdown dynamically removes the targets when a LOST notification happens as well which is good.

image

**Comment by andrewazores** [comment]
Okay, weird. Not sure why the scaling isn't coming through anymore. I guess that's a separate bug to do with which resources we are watching or how we handle the events. At least now we are reconnecting and resuming the stream of events if we lose it.

**Comment by andrewazores** [comment]
```bash
$ make sample_app # one replica, LOST and FOUND are emitted
$ oc scale --replicas=2 deployment/vertx-fib-demo # FOUND notification is emitted
$ oc scale --replicas=1 deployment/vertx-fib-demo # LOST and FOUND notifications are emitted for BOTH of the replicas - looks like a watch MODIFIED event was picked up
$ oc scale --replicas=0 deployment/vertx-fib-demo # no notification
$ oc scale --replicas=1 deployment/vertx-fib-demo # LOST and FOUND notifications are emitted again
$ oc scale --replicas=2 deployment/vertx-fib-demo # LOST and FOUND notifications are emitted for BOTH replicas
```

File: src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java [hunk 1]
```diff
@@ -94,62 +96,97 @@ public class KubeApiPlatformClient extends AbstractPlatformClient {
...
+                                                        new IllegalArgumentException(
+                                                                action.toString()));
+                                                return;
+                                        }
+                                    }
+
+                                    @Override
+                                    public void onClose(WatcherException watcherException) {
+                                        if (watcherException.isHttpGone()) {
+                                            // https://stackoverflow.com/questions/61409596/kubernetes-too-old-resource-version
```
Comment (ebaron) [inline src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java:169]: What about using the SharedInformer from this example instead of a Watch? Sounds like it could be less error prone.

Comment (andrewazores) [reply src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java:169]: I can give it a try and see how it behaves.

Comment (andrewazores) [reply src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java:227]: I just pushed a commit so you can see what I tried there. The kubernetes-client API in the version we're using is a little different from what the example in the SO post said, but I believe what I did is the equivalent. It just doesn't seem to work however - I'm not receiving any events at all.

Comment (andrewazores) [reply src/main/java/io/cryostat/platform/internal/KubeApiPlatformClient.java]: Fixed. I rewrote the commit history and just replaced it with the working implementation after updating the fabric8 version and replacing the Watch with an Informer.

**Comment by andrewazores** [comment]
I think everything works as expected now. The original PR body text has been updated with a revised description now that the change is deeper, and there are new test images available.

**Comment by maxcao13** [comment]
Wow, great job. After testing the new image on crc, both scaling and deleting the resource result in proper LOST and FOUND notifications being emitted.

**Comment by andrewazores** [comment]
I'm working on one last little commit here to memoize the discovery tree computation (`GET /api/v2.1/discovery`). If the Endpoints store hasn't changed then the leaves of the tree are all the same and therefore we would compute all the same paths back up to the root, so we may as well just retain that result and return it immediately rather than recalculating it again, which involves a bunch more k8s API calls. The "get all service refs" (`GET /api/v1/targets)` result won't be memoized because that doesn't require any new API calls to be made anymore either, it just does some light manipulations of the data in the Endpoints store to transform it into the List<ServiceRef>, and no additional cascading API calls. Probably not worth bothering with memoizing that.

**Comment by andrewazores** [comment]
Last two commits implement that quick memoization of the discovery tree and also ensure that the Informer is started before we try to access its store. This also means that if the informer unexpectedly stops it will be restarted when a targets list or discovery tree query is issued. That mechanism will stop working after #1028 so I'll need to revisit it again to figure out some other way to check the Informer's status and restart it as needed.

`quay.io/andrewazores/cryostat:k8s-rewatch-14` and `quay.io/andrewazores/cryostat-operator:k8s-rewatch-14` have the latest changes.

File: pom.xml [hunk 2]
```diff
@@ -73,7 +73,7 @@
   <org.apache.commons.validator.version>1.7</org.apache.commons.validator.version>
   <org.apache.commons.io.version>2.8.0</org.apache.commons.io.version>
   <org.apache.httpcomponents.version>4.5.13</org.apache.httpcomponents.version>
-  <io.fabric8.client.version>5.4.1</io.fabric8.client.version>
+  <io.fabric8.client.version>5.12.3</io.fabric8.client.version>
```
Comment (ebaron) [inline pom.xml:76]: Are we able to use 5.12.2 instead to sync with Quarkus 2.7? https://github.com/quarkusio/quarkus/blob/8ecbe2c5282b26227139798e610cb98a176db974/bom/application/pom.xml#L171

Comment (andrewazores) [reply pom.xml]: Done in last push, seems to be working fine.

**Review by ebaron — APPROVED** [review]
Works well!

**Comment by andrewazores** [comment]
@maxcao13 @tthvo any further comments?

**Review by tthvo — APPROVED** [review]
Tested on crc and worked well!! Awesome!

**Review by maxcao13 — APPROVED** [review]
Looks good from my end as well. Awesome job!

**Comment by maxcao13** [comment]
@andrewazores I believe this solves #1038 as well, correct?

**Comment by andrewazores** [comment]
Ah yes, good catch, thanks.
